from setuptools import setup

setup(
    name='differentiable-voronoi',
    version='0.0.4',
    packages=['differentiable_voronoi'],
    url='https://github.com/SergeiShumilin/differentiable-voronoi',
    license='',
    author='Sergei Shumilin',
    author_email='ishumili@gmail.com',
    description='differentiable Voronoi tessellation',
    install_requires=['contourpy==1.2.1',
                      'cycler==0.12.1',
                      'filelock==3.14.0',
                      'fonttools==4.52.1',
                      'fsspec==2024.5.0',
                      'importlib_resources==6.4.0',
                      'Jinja2==3.1.4',
                      'kiwisolver==1.4.5',
                      'MarkupSafe==2.1.5',
                      'matplotlib==3.9.0',
                      'mpmath==1.3.0',
                      'networkx==3.2.1',
                      'numpy==1.26.4',
                      'packaging==24.0',
                      'pillow==10.3.0',
                      'pyparsing==3.1.2',
                      'python-dateutil==2.9.0.post0',
                      'scipy==1.13.1',
                      'shapely==2.0.4',
                      'six==1.16.0',
                      'sympy==1.12',
                      'torch==2.3.0',
                      'tqdm==4.66.4',
                      'trimesh==4.4.0',
                      'typing_extensions==4.12.0',
                      'zipp==3.19.0']
)
